var index = [
    { episode: "235", url: "https://www.youtube.com/watch?v=uWFeV6G1EZE" },
    { episode: "236", url: "https://www.youtube.com/watch?v=vUOLfybOzdM" },
]

episode236Url = "https://www.youtube.com/watch?v=vUOLfybOzdM"
episode235Url = "https://www.youtube.com/watch?v=uWFeV6G1EZE"

// NOTE: Chat vs. Offtopic???
var episode236 = [
    { time: "00:00", category: "Chat", text: "Chat" },
    { time: "01:50", category: "Chat", text: "Jessie's Gingerade Kombucha" },
    { time: "02:49", category: "Chat", text: "Free Kombucha and Lies" },
    { time: "03:21", category: "Chat", text: "Opera Rehersal" },
    { time: "03:38", category: "", text: "Old font symbols" },
    { time: "05:06", category: "Chat Question", text: "Ancient Font looks like Ogham (\"I have missed many weeks. Is this supposed to look like Ogham?\" - George Corley)" },
    { time: "05:25", category: "Chat", text: "Pronunciation of Ogham" },
    { time: "06:05", category: "", text: "David highlights preferred glyphs in red" },
    { time: "06:35", category: "Poll", text: "Poll discussion (5 options)" },
    { time: "08:02", category: "Poll", text: "Winner: Option A with diacritic chosen for flipped l" },
    { time: "08:23", category: "Chat", text: "\"The poll was a bit poll-arizing\" - Miles" },
    { time: "09:23", category: "", text: "Jessie double checks poll for sound of new glyph" },
    { time: "09:42", category: "", text: "Places new glyph in font" },
    { time: "10:24", category: "Chat Question", text: "Polls located on Patreon (\"I keep forgetting. Where is the poll conducted?\" - animefan25)" },
    { time: "10:40", category: "", text: "Patreons have 7 days left for vote on next language" },
    { time: "11:37", category: "Chat Question", text: "This episode is last Tpaalha episode (\"Does that mean this is the last Tpaalha ep?\" - Miles)" },
    { time: "11:48", category: "Chat", text: "Pronunciation of Tpaalha" },
    { time: "12:21", category: "Chat", text: "Chocolate chip episode (\"It's a chocolate chip episode because it's bittersweet\" - Miles)" },
    { time: "12:48", category: "Chat Question", text: "No greetings yet in Tpaalha (\"We do have greetings by now right?\" - Noel Strüning)" },
    { time: "13:16", category: "", text: "David eats chocolate chips" },
    { time: "13:52", category: "", text: "Goal for today - versions of numbers, period, question mark, and deciding on paragraph and sentence brackets" },
    { time: "14:45", category: "", text: "Discussion on hyphen glyph" },
    { time: "15:02", category: "", text: "David makes hyphen glyph" },
    { time: "15:27", category: "Chat", text: "Gin gins and Langtime Adventure (\"trying to open my new box of double strength gin gins ... a soothing travel treat, because langtime is such an adventure\" - Rag Doll)" },
    { time: "15:51", category: "Chat", text: "Gingered Bread" },
    { time: "16:17", category: "", text: "Em dash" },
    { time: "17:00", category: "", text: "Jessie becomes out of sync" },
    { time: "17:33", category: "Chat", text: "Gin gins (\"yeah it's like a hard boiled lolly but ginger. The soft ones have palm oil so we don't get those\" - Rag Doll)" },
    { time: "17:42", category: "Chat", text: "\"David is putting the 'boo' in 'Kombucha'\" - Matthijs Krul" },
    { time: "17:51", category: "Chat", text: "\"I just realised the spain-without-s joke doesn’t work\" - Noel Strüning" },
    { time: "18:07", category: "Chat", text: "Kombucha label (\"The weirdest thing about the kombucha at work was the marketing on the label was just straight up Orientalism\" - George Corley)" },
    { time: "18:37", category: "Chat", text: "Beverly Hills" },
    { time: "20:15", category: "Chat", text: "Beverly Hillbillies Mansion (\"I just want to see the mansion they used to Beverly Hillbillies if it actually exists\" - George Corley)" },
    { time: "20:41", category: "Chat", text: "Universal Studios Lots" },
    { time: "21:13", category: "Chat", text: "Jem show (\"When I heard the word synergy, I think Jem.\" - animefan25)" },
    { time: "21:47", category: "", text: "David cleans up font" },
    { time: "22:30", category: "", text: "David scrolls to page 27 to see roots" },
    { time: "22:47", category: "", text: "Discusses \"psyity\" devoicing" },
    { time: "23:41", category: "Chat Question", text: "About Jem and the Hollograms show (\"What’s jem? We only have czechoslovak childrens series\" - Noel Strüning)" },
    { time: "24:18", category: "", text: "Reason for devoicing of \"psyity\" - Rule 21" },
    { time: "24:29", category: "Chat", text: "David explains crucial part of \"Jem and the Hollograms\" name" },
    { time: "26:01", category: "Chat", text: "80s Hannah Montana (\"So Jem and the Holograms is like the 80's version of Hannah Montana?\" - Miles)" },
    { time: "26:11", category: "Chat Question", text: "\"I haven't seen it but is it a bit teeny boppy?\" - Rag Doll" },
    { time: "26:30", category: "Chat", text: "\"that sounds really bizarre\" - Matthijs Krul" },
    { time: "26:48", category: "", text: "Jessie asks about devoicing of \"psyity\"" },
    { time: "27:02", category: "", text: "Jessie's plans on word creation (Verbs and Adjectives)" },
    { time: "27:24", category: "", text: "David's plans on favorite J glyph" },
    { time: "27:48", category: "", text: "Jessie checks only Adjective (\"long\")" },
    { time: "28:05", category: "", text: "Jessie discusses basic Adjectives - short, wide, narrow, dark, light" },
    { time: "29:08", category: "Chat", text: "Miles suggests wet/dry; hot/cold" },
    { time: "29:15", category: "Chat", text: "David discusses days when brain isn't working" },
    { time: "29:57", category: "", text: "Jessie discuses Adjectives list and long/short" },
    { time: "30:16", category: "", text: "David mentions (incorrectly) there are no prenominal modifiers. But there are immediate postnominal modifiers, including demonstratives" },
    { time: "30:57", category: "Chat", text: "\"tlaan is prenominal\" - Evan Swart" },
    { time: "31:34", category: "", text: "Discussion on Prenominal Adjectives" },
    { time: "32:07", category: "Chat", text: "Silverchair (\"my first concert was Silverchair/Frenzal Rhomb/Pangaia\" - Rag Doll)" },
    { time: "32:37", category: "Chat", text: "Writeup on Adjectives (\"theres a whole adjectives writeup ... itincludes an explanation of prenominal adjectives @LangTime Studio\" - Evan Swart)" },
    { time: "33:29", category: "Chat", text: "Jessie's Fuzzy Brain and Kombucha Cultures" },
    { time: "34:10", category: "Chat", text: "Adelaide name (\"I was 15, it was at Adelaide Uni, lots of bands\" - Rag Doll)" },
    { time: "34:24", category: "Chat", text: "\"Jessie is the Oracle\" - Miles" },
    { time: "34:29", category: "", text: "Jessie discusses Adjective root options \"ubu\" and \"psyity\"" },
    { time: "35:09", category: "", text: "David adds diacritic to question mark and single quote glyphs" },
    { time: "35:18", category: "", text: "Jessie enters the new adjective forms \"ubu\" and \"psyity\"" },
    { time: "35:53", category: "Chat Question", text: "\"are these going to be prenominsal? @LangTime Studio\" - Evan Swart" },
    { time: "36:08", category: "", text: "David hums (presumably a Silverchair song called \"Tomorrow\")" },
    { time: "36:16", category: "Chat", text: "Suggestions for \"ubu\" to mean \"big\" or \"dark\"" },
    { time: "37:05", category: "", text: "Jessie asks chat if \"ubu\" and \"psyity\" should be a pair for \"big\" and \"small\", respectively" },
    { time: "37:30", category: "", text: "Jessie has spacebar problems" },
    { time: "37:46", category: "", text: "\"ubu\" and \"psyity\" picked for words \"big\" and \"small\", respectively" },
    { time: "38:31", category: "", text: "David tests new glyphs for question mark and single quote" },
    { time: "38:57", category: "Chat", text: "David asks for meaning of \"ganz gut\". Jessie responds that it means \"entirely good\"." },
    { time: "39:23", category: "Chat Poll", text: "Position of diacritic on question mark glyph (A = centered diacritic; B = right-aligned diacritic)" },
    { time: "41:53", category: "Chat Poll", text: "Winner: A = 10; B = 6" },
    { time: "41:58", category: "Kopiko Time", text: "Celebrate, with Kopiko, David being right on number of A votes" },
    { time: "42:30", category: "Chat", text: "\"the average person only has two eyes, it's reasonable that you were surprised bib has three\" - Magpie" },
    { time: "43:01", category: "", text: "David discusses kerning of question mark glyph" },
    { time: "44:15", category: "", text: "David looks at question mark glyph again" },
    { time: "44:30", category: "", text: "Jessie asks if spelling/typing of epsilon in proto-forms/ancient orthography is an \"e\". David roundaboutly answers yes." },
    { time: "46:54", category: "Chat", text: "Biblaridion as Nickelodeon Jingle" },
    { time: "47:11", category: "Chat", text: "Jessie and David adjust their air conditioners" },
    { time: "47:54", category: "Chat", text: "\"If it wasnt an adjective, ubu sounds like a cucumber\" - Noel Strüning" },
    { time: "48:17", category: "Chat", text: "\"Combine the Kopiko with the choco chip for a mocha kopiko!\" - Miles" },
    { time: "48:30", category: "Chat", text: "Comment regarding David's notifications (\"We cant see it, its behind jessie\" - Noel Strüning)" },
    { time: "48:39", category: "Chat Question", text: "Ubu Production Company (\"Isn't ubu the name of a production company?\" - animefan25)" },
    { time: "50:33", category: "", text: "David creates new period and question mark glyphs" },
    { time: "50:51", category: "Chat", text: "J.J. Abrams' Bad Robot (\"I recall bad and robot's thing like that\" - Chris Helvey)" },
    { time: "51:08", category: "Chat", text: "Watching TV as a child" },
    { time: "53:22", category: "Chat", text: "People's Court, Judge Judy, and Hot Bench" },
    { time: "55:21", category: "", text: "Jessie asks if modern romanized form \"tymʲout\" looks fishy. Romanizer appears broken in lexurgy. Should be \"tymyout\"." },
    { time: "57:04", category: "Chat", text: "\"I'll have to take a look when I'm at my other computer\" - Meamer" },
    { time: "57:27", category: "Chat", text: "Meamer's quite smiley (\"I've been here but very quite 🙂\" - Meamer)" },
    { time: "57:43", category: "Chat", text: "\"Oh no I'm catching Beetlejuice powers from Bib!\" - Meamer" },
    { time: "57:52", category: "", text: "Jessie's two suggestions, \"sfaku\" and \"tymyout\"" },
    { time: "58:12", category: "", text: "Pronunciation of \"tymyout\"" },
    { time: "58:46", category: "", text: "Jessie suggests \"tymyout\" should mean \"wet\" and \"sfaku\" should mean \"dry\"." },
    { time: "59:49", category: "", text: "Jessie enters new words. \"t\" words are banned." },
    { time: "01:00:50", category: "Chat Poll", text: "Whether to keep the old font's paragraph and sentence initial markings in the modern font. If so, should they be simplified?" },
    { time: "01:06:47", category: "", text: "David questions how to stylize the sentence initial marker" },
    { time: "01:08:09", category: "", text: "Jessie enters proto-forms while David experiments with sentence initial marker" },
    { time: "01:10:38", category: "Chat", text: "polysemy vs. semelparity (\"For some reason, I keep getting mixed up between polysemy and semelparity\" - Biblaridion)" },
    { time: "01:11:33", category: "Chat", text: "\"Well clearly I don't, because I keep thinking it means polysemy\" - Biblaridion" },
    { time: "01:11:58", category: "Chat", text: "Definition of Semelparity" },
    { time: "01:13:05", category: "", text: "Discussion on words for \"short\"" },
    { time: "01:13:35", category: "", text: "David finally notices Jessie is out of sync" },
    { time: "01:13:48", category: "Chat", text: "Cloudiness of Kombucha - \"Live Cultures\"" },
    { time: "01:14:11", category: "Chat", text: "Alk suggests \"iet\"" },
    { time: "01:14:38", category: "", text: "Jessie suggests \"koy\" for \"short\"" },
    { time: "01:15:08", category: "", text: "Jessie asks for more suggestions and bans \"k\" words" },
    { time: "01:15:36", category: "", text: "David asks for thoughts on new glyphs for sentence initial marking" },
    { time: "01:15:57", category: "", text: "No opinions on new glyphs for sentence initial markings. Going with Jessie's suggestion of using glyph without diacritic." },
    { time: "01:17:08", category: "Chat", text: "New root \"myir\" (\"mirə => ˈmʲiɻ => myír\" - Jake Penny)" },
    { time: "01:17:41", category: "Chat", text: "\"make more knan s\" - Chris Helvey" },
    { time: "01:19:07", category: "Chat", text: "Language Pronunciation Woes (\"I'm gonna miss the cluster tomfoolery of this language\" - Miles)" },
    { time: "01:20:11", category: "", text: "Glyphs left to do - Just the numbers (0 through 6)" },
    { time: "01:22:34", category: "Chat", text: "Jessie's math score on GRE (which David confuses with ACT) was 780. Analytic score was 800." },
    { time: "01:24:25", category: "Chat Question", text: "GRE Scoring Changes (\"I don't remember how GRE scoring works, but I do remember that I got exactly 1 point less than perfect.\" - Logan Kearsley)" },
    { time: "01:24:53", category: "", text: "David discusses how glyph for number four will look." },
    { time: "01:25:23", category: "Chat", text: "\"Exactly one of whatever the units were.\" - Logan Kearsley" },
    { time: "01:25:34", category: "Chat", text: "\"But I did get a perfect 1600 SAT. 🙂\" - Logan Kearsley" },
    { time: "01:25:54", category: "Chat", text: "ACT vs. SAT. David teases about ACT asking about tractors. Jessie stares David down." },
    { time: "01:26:27", category: "Chat", text: "\"1450 is still pretty good!\" - Logan Kearsley" },
    { time: "01:26:38", category: "Chat", text: "\"ACT ftw\" - Miles" },
    { time: "01:26:53", category: "Chat Question", text: "U.S. Standardized Pre-college Tests (\"Do I try to find out what an SAT is now...?\" - Thiemo N.)" },
    { time: "01:27:50", category: "Chat", text: "\"Officially, \"SAT\" doesn't stand for anything anymore. It's like KFC.\" - Logan Kearsley" },
    { time: "01:28:32", category: "Chat", text: "\"it was originally the Scholastic Aptitude Test\" - Evan Swart" },
    { time: "01:28:43", category: "", text: "The glyph for the number five - a window" },
    { time: "01:29:46", category: "Chat", text: "\"ACT was originally the American College Testing\" - Evan Swart" },
    { time: "01:29:55", category: "Chat", text: "\"@Logan Kearsley Which is weird for KFC, since their Chinese name is still 肯德基 \"Kentucky\"\" - (George) Corley English" },
    { time: "01:30:10", category: "Chat", text: "Bill Gates trouble" },
    { time: "01:30:50", category: "", text: "Diamond glyph" },
    { time: "01:31:14", category: "Chat", text: "\"BRB gotta get some BBQ\" - Miles" },
    { time: "01:31:56", category: "Chat", text: "\"Diamond skewed like the lines?\" - The Applesauce Project" },
    { time: "01:33:00", category: "Chat", text: "Fondest memories of Season 2" },
    { time: "01:35:38", category: "Chat", text: "David says \"mathily\" weird" },
    { time: "01:36:06", category: "Chat", text: "\"I'm going to post my vegan falafels I made\" - Rag Doll" },
    { time: "01:36:13", category: "Chat", text: "\"just the language is absolutely insane grammatically\" - Evan Swart" },
    { time: "01:36:24", category: "Chat Question", text: "5 Languages for Game; 3 more seasons for mouse, dog, and cat (\"How many languages do y'all plan on doing before you have enough for the game?\" - (George) Corley English)" },
    { time: "01:36:42", category: "", text: "David finishes terrible glyph :D"  },
    { time: "01:38:52", category: "Chat Question", text: "Start of Next Language/Season (\"When is the next language starting? 😁\" - Christian Seibold (Krixano))" },
    { time: "01:39:14", category: "Chat", text: "\"Jessie's the star of the show\" - Chris Helvey" },
    { time: "01:39:53", category: "Chat", text: "\"khwnoulh\" (\"I know we left the topic of pronounciation but xɻənɨɭ becomes khwnoulh so that is a treat\" - Noel Strüning)" },
    { time: "01:40:13", category: "Chat Question", text: "Langtime languages as improvement over David's old languages? Not really (\"i mean does the language, have to be like zhyler? it could take on a life of its own!!!\" - Evan Swart)" },
    { time: "01:41:05", category: "", text: "David's concerns - window glyph, similarity of glyphs 1-3, and two versions of glyph 6" },
    { time: "01:42:09", category: "Chat Poll", text: "Pick out of two glyphs for 6 (A = diamond, B = upsidedown triangle, C = do something different)" },
    { time: "01:42:57", category: "Chat Poll", text: "Winner: C (do something different for glyph of number 6) wins overwhelmingly within seconds" },
    { time: "01:43:29", category: "", text: "David tries bottom half of diamond" },
    { time: "01:43:50", category: "Chat Question", text: "Patreons picking next language for next patreon livestreams (\"So will the patrons pick between Engala and Tpaalha in our livestreams or will we move on to mostly Tpaalhaing now?\" - Jake Penny)" },
    { time: "01:44:17", category: "Chat Poll", text: "Half Diamond for glyph for number 6?" },
    { time: "01:44:40", category: "", text: "Problem with boxy number glyphs - should be less room above line than below. David corrects this." },
    { time: "01:44:56", category: "Chat", text: "Annotations" },
    { time: "01:45:09", category: "Chat Question", text: "Distinguishing between glyphs for numbers 1, 2, and 3 (\"can we bring back the cross bars?\" - Jake Penny)" },
    { time: "01:45:34", category: "", text: "David asks Jessie about tops of square number glyphs" },
    { time: "01:46:20", category: "Chat", text: "\"also the angtime episode guide/ timestamping initiative that kinda got sidelined since S1\" - Evan Swart" },
    { time: "01:49:18", category: "Chat", text: "\"For 1-3, tighten the kerning so that 3 is as wide as the glyph for 4.\" - The Applesauce Project" },
    { time: "01:48:00", category: "", text: "David tries his idea of top connectors for glyphs of numbers 1-3. Jessie likes it." },
    { time: "01:51:26", category: "Chat", text: "\"Yellow is my favourite colour\" - Noel Strüning" },
    { time: "01:52:10", category: "", text: "David tries three new ideas for glyph of number 6" },
    { time: "01:55:55", category: "Chat", text: "Checkmark suggestion for glyph of number 6 (\"what about the check mark with top half of 1\" - Chris Helvey)" },
    { time: "01:56:06", category: "Chat", text: "Ligature suggestion for glyph of number 6 (\"What's the word for six? Make a ligature, make it weird\" - (George) Corley English)" },
    { time: "01:56:27", category: "Chat", text: "Inverted A suggestion for glyph of number 6 (\"what about something like an inverted capital A?\" - Jake Penny)" },
    { time: "01:57:32", category: "Chat Question", text: "Logographic Fonts; David and Jessie's secret conlang project with logographic script (\"Is it possible to create a digital font for a conscript that is a logography?\" - Beatrice Palmer)" },
    { time: "01:59:11", category: "Chat Poll", text: "David's new glyph for number 6" },
    { time: "02:00:00", category: "", text: "David quickly creates glyph for zero, which he forgot to do." },
    { time: "02:01:11", category: "Chat", text: "Jessie's Sidenote: Emo's Pizza" },
    { time: "02:01:50", category: "Chat", text: "Motherland Language (\"I like Motherland and the conlang is neat\" - Chris Helvey)" },
    { time: "02:02:14", category: "Chat", text: "Why a zero? Reason: There already was a zero in the proto-language." },
    { time: "02:03:10", category: "Chat", text: "Where to watch Motherland outside of US (\"it's on either disney+ or netfix here since we don't hav hulu\" - Evan Swart)" },
    { time: "02:03:45", category: "Chat", text: "David's Gameshow opportunity taken away due to Motherland work" },
    { time: "02:04:34", category: "", text: "Font done! Only kerning and flipping left." },
    { time: "02:05:50", category: "", text: "David and Jessie tease next episode's surprise." },
    { time: "02:06:33", category: "", text: "Season 2 Podcast episodes released publicly soon. Season 3 next week." },
    { time: "02:07:28", category: "", text: "Surprise Hint? Hint possibly already given in episode previously, from a suggestion by David." },
    { time: "02:09:10", category: "Chat", text: "Dreaming of Kopiko sponsorship and T-shirts" },
]
const episode236Fuse = new Fuse(episode236, { findAllMatches: true, shouldSort: true, includeScore: true, keys: [{ name: 'category', weight: 0.7 }, { name: 'text', weight: 0.3 }], threshold: 0.5, distance: 120 })

var episode235 = [
    { time: "00:00", category: "Chat", text: "Chat" },
    { time: "00:58", category: "Main", text: "David shows Matthijs the classifiers from Sheli, David's contratone language" },
    { time: "03:12", category: "Chat", text: "Sheli's writing system (\"That writing system looks badass!\" - Miles)" },
    { time: "03:22", category: "Main", text: "Chair problems" },
    { time: "03:42", category: "Chat", text: "Aweful execution of Sheli's writing system, according to David" },
    { time: "05:20", category: "Chat", text: "Dictionary entries for classifiers" },
    { time: "06:02", category: "Chat Question", text: "High Valyrian adjectives History (\"Random question: Are we allowed to know the history behind the alternation that happens with High Valyrian adjectives depending on whether they come before or after the noun?\" - Biblaridion)" },
    { time: "06:50", category: "Chat", text: "Latin avoids repetition of rhyming cases in Poetry" },
    { time: "07:17", category: "Chat", text: "John Milton decried rhyming couplets in Paradise Lost's preface" },
    { time: "07:58", category: "Chat", text: "Jessie's now ready to start (\"Hey! I'm here!\" - Minnie Scott)" },
    { time: "08:09", category: "Chat", text: "David asks Jessie how he previously fixed his chair as he wrestles with it. He successfully fixes it." },
    { time: "08:52", category: "Poll", text: "Patreon reciprocal strategies vote on pages 7-8 is discussed" },
    { time: "10:49", category: "Poll", text: "Reciprocal strategies winner: Tail to Tail (Maximally Reduced). Received 15 votes." },
    { time: "11:28", category: "Chat", text: "Jake's date (\"​Hey guys! Just finished with my date. Did anything happen before the poll results?\" - Jake Penny)" },
    { time: "11:50", category: "Chat", text: "Matthijs' sink (\"I am highly diligent about keeping my sink clear and clean\" - Matthijs Krul)" },
    { time: "12:06", category: "Chat", text: "Concerts in the park" },
    { time: "12:18", category: "Chat", text: "\"We had a cheeky Nandos ... ​and watched drag race\" - Jake Penny" },
    { time: "12:45", category: "Main", text: "David realizes notifications aren't disabled" },
    { time: "13:03", category: "Chat", text: "How David learned about Nandos - controversial commercials" },
    { time: "13:42", category: "Chat", text: "​Controversiamercials and Controversiamals (\"​Controversiamercials?\" - Minnie Scott)" },
    { time: "14:14", category: "Chat", text: "2am Funerals (\"We didn't talk about Brexit but his we did talk about his nan dying (the funeral was at 2am this morning)\" - Jake Penny)" },
    { time: "15:30", category: "Main", text: "David starts entering reciprocal pronoun \"zyizyis\" (\"each other\") from poll into dictionary" },
    { time: "15:55", category: "Main", text: "Jessie explains dictionary being updated with all backentries" },
    { time: "16:38", category: "Chat", text: "\"I'm meeting my s/o for the first time in person tomorrow in Iowa 🙂\" - Minnie Scott" },
    { time: "18:29", category: "Poll", text: "Discussing second poll on David and Jessie's name meanings in Tpaalha" },
    { time: "21:19", category: "Poll", text: "Poll Winners for David and Jessie's name meanings in Tpaalha are \"Summit (of a mountain)\", and \"bank of a river\", respectively" },
    { time: "22:19", category: "Chat", text: "\"Whoa Jessie's gone soooo far out of sync\" - Meamer" },
    { time: "23:07", category: "Chat", text: "Cowslip - a type of flower. Comes from Old English \"cūslyppe\" ('Cow' + 'Slime'), meaning cow slober or dung" },
    { time: "25:35", category: "Main", text: "Asking if Jessie's sync issues are bad enough to need fixing" },
    { time: "25:53", category: "Chat", text: "June 24th - Jessie's 3rd birthday of the year. Actually, 1 month anniversary of 40th birthday" },
    { time: "26:36", category: "Chat", text: "\"​I see Jessie's mouth moving at pretty much the same time as the mouth-noises.\" - Logan Kearsley" },
    { time: "26:50", category: "Chat", text: "David marvels at current date in Australia, but is disappointed at not being invited there for a talk." },
    { time: "27:12", category: "Chat Question", text: "Jessie's \"3 birthdays\" - mistakenly filled out form that gave Jessie a different birthday, and friend getting her birthday 1 month off (\"how do you get 3 b'days?\" - Rag Doll)" },
    { time: "28:23", category: "Main", text: "Fixing Jessie's sync issues" },
    { time: "29:22", category: "Chat", text: "\"Ηαρργ βιρτδαγ\" - Noel Strüning" },
    { time: "29:37", category: "Main", text: "Ready to enter Jessie and David's names into dictionary" },
    { time: "29:53", category: "Main", text: "Jessie shows off work of listing dictionary order of inflected forms for nouns and verbs on page 38. David suggests moving it to page 36." },
    { time: "30:42", category: "Chat", text: "Jessie is \"shooting daggers\" at David" },
    { time: "33:00", category: "Main", text: "Dictionary entries for Jessie and David's names in Tpaalha, \"dabyid\" and \"dyisi\", respectively. David misspells \"summit\" as \"sumit\"." },
    { time: "34:30", category: "Main", text: "David switches to Lexurgy to determine how the dual suffix attaches to words that end with a shwa." },
    { time: "37:28", category: "Main", text: "Next steps - David will do font stuff, and Jessie will do more vocab creation. Jessie checks Patreon name entry submissions." },
    { time: "38:37", category: "Chat", text: "\"​Tpaalha uses a Significant Other Verb word order\" - (Graham) Meamer" },
    { time: "39:26", category: "Chat", text: "Laughing out lou (\"@Meamer Just laughed out lou ... *loud\" - Minnie Scott)" },
    { time: "39:47", category: "Chat", text: "Jessie also needs a cup of tea (\"I don't think my cup of tea is coming. I think someone fell asleep\" - Rag Doll)" },
    { time: "39:58", category: "Chat", text: "Jessie would date a verb. David says \"verbs are nothing but trouble\". (\"who would date a verb though?? awful word class\" - Matthijs Krul)" },
    { time: "40:29", category: "Main", text: "Left side of document, or whole thing? Mostly left." },
    { time: "41:45", category: "Chat", text: "Jessie has flashback about David asking about the top of his head" },
    { time: "42:12", category: "Chat", text: "Snacks" },
    { time: "42:45", category: "Main", text: "David starts modern font work for Tpaalha" },
    { time: "42:56", category: "Chat", text: "Vegan Pizza and Pasta (\"I have left over vegan pizza and pasta\" - Rag Doll)" },
    { time: "43:04", category: "Chat", text: "Munching and pronunciation (\"​Maybe the munching will help with Tpaalha pronounciation\" - Miles)" },
    { time: "43:15", category: "Main", text: "Discussion on modern spelling for Tpaalha" },
    { time: "44:10", category: "Chat", text: "\"*teleports some vegan pizza and pasta to Jessie*\" - Rag Doll" },
    { time: "44:42", category: "Main", text: "David discusses flip form diacritics in Tpaalha's modern font" },
    { time: "46:25", category: "Chat", text: "Jessie drools over Rag Doll's pizza (\"the pizza has potato, vegan cheese, pineapple, basil, artichoke, pumpkin, mushroom and olives\" - Rag Doll)" },
    { time: "47:10", category: "Main", text: "David questions previous math work for placement of diacritic" },
    { time: "49:27", category: "Chat Poll", text: "Meaning for new root \"tibosh\"" },
    { time: "50:48", category: "Chat", text: "\"loud\" suggestion - adjectives derived from nouns in Tpaalha, so need noun and verb suggestions (\"loud\" - Beatrice Palmer)" },
    { time: "51:08", category: "Chat", text: "Suggestions for root \"tibosh\": to burrow, to hide, to fight, tick, frown, to bite, scratch, kill" },
    { time: "52:54", category: "Chat", text: "David's suggestion for \"arguing fighting\" to mean \"mouse fighting\"" },
    { time: "53:20", category: "Main", text: "David's perfectly centered diacritic" },
    { time: "54:00", category: "Chat", text: "Mice Summits (\"​the mice would hold summits\" - Jake Penny)" },
    { time: "54:10", category: "Main", text: "Jessie chooses meaning \"to burrow, to hide\" for new root \"tibosh\" and enters it into the dictionary" },
    { time: "56:35", category: "Main", text: "David tries to position the diacritic to his liking" },
    { time: "58:32", category: "Chat", text: "Matthijs living in the U.S. (\"​hall pass... that brings up memories of living in the US\" - Matthijs Krul)" },
    { time: "58:48", category: "Main", text: "Jessie asks about spelling of proto-form retroflex s" },
    { time: "59:20", category: "Chat", text: "David's Princeton Jelousy (\"​yeah when I was 8 I lived in glorious Princeton, NJ for a year\" - Matthijs Krul)" },
    { time: "01:00:31", category: "Chat", text: "\"​yeah my mom did stuff at the Institute for Advanced Study I believe\" - Matthijs Krul" },
    { time: "01:01:41", category: "Chat", text: "\"yeah my mother is (now retired) a professor of ancient Greek history\" - Matthijs Krul" },
    { time: "01:02:43", category: "Chat", text: "Jessie's hearty hellos and David's hms (\"my parents are visiting in a few weeks actually\" - Matthijs Krul)" },
    { time: "01:02:57", category: "Main", text: "David recognizes incorrect positioning of some of the diacritics" },
    { time: "01:03:52", category: "Chat", text: "\"I will say hi for the conlang show! I have mentioned it before :)\" - Matthijs Krul" },
    { time: "01:03:58", category: "Chat", text: "Quantum Leap thoughts (\"oh boy\" - Jason L)" },
    { time: "01:04:09", category: "Chat", text: "David sings a terrible song" },
    { time: "01:04:32", category: "Chat Poll", text: "Jessie asks for suggestions for a word for \"fox\" - psyity, ubu, khoi" },
    { time: "01:05:03", category: "Main", text: "David realizes the problem with the font - his IPA keyboard was on" },
    { time: "01:05:37", category: "Chat Question", text: "Sam does encounter Buddy Holly as a kid (\"Big fan of Quantum Leap. Did Sam encounter Buddy Holly?\" - animefan25)" },
    { time: "01:06:46", category: "Chat", text: "\"​Didn't he inhabit Elvis at one point?\" - The Applesauce Project" },
    { time: "01:08:09", category: "Chat", text: "Quantum Leap scripts (\"​The best man at my wedding's dad was in the final episode of Quantum Leap. I have his copy of the shooting script with the original scifi ending\" - The Applesauce Project)" },
    { time: "01:09:58", category: "Chat", text: "Babylon 5 and E.R. (\"​He also played Bester's boss on Babylon 5 and a fireman on E.R. ... On E.R. his character married his real life wife who was one of the background nurses.\" - The Applesauce Project)" },
    { time: "01:11:07", category: "Chat Question", text: "\"​jessie have you watched any star trek?\" - Jonathan" },
    { time: "01:11:45", category: "Main", text: "Jessie selects final form for \"fox\" as \"khoi\" and enters it into the dictionary" },
    { time: "01:13:41", category: "Chat Poll", text: "David asks for opinions on placement of diacritic being 100 from vertical line rather than centered above the vertical line. The latter wins." },
    { time: "01:16:26", category: "Chat", text: "\"​There's a rainbow unicorn drink!!!!\" - Jake Penny" },
    { time: "01:19:50", category: "Chat Poll", text: "Diacritic centering over v character vs. left of vertical line. The latter choice made previously remains." },
    { time: "01:20:34", category: "Kopiko Time", text: "Kopiko Celebration" },
    { time: "01:20:44", category: "Chat Question", text: "Vegan Kopiko (\"Would vegan kopiko make sense?\" - animefan25)" },
    { time: "01:22:06", category: "Chat", text: "Cheers with eye contact in Germany" },
    { time: "01:22:49", category: "Chat", text: "\"yeah in NL too, you have to make eye contact and do it every round\" - Matthijs Krul" },
    { time: "01:22:57", category: "Chat", text: "\"​In hungarian, you say the same word for cheers and for bless you, its weird\" - Noel Strüning" },
    { time: "01:25:12", category: "Chat", text: "\"​Some day we will make eye contact Jessie. World better watch out for what happens after that. ... ​It might summon something fierce and magical\" - Minnie Scott" },
    { time: "01:25:43", category: "Chat", text: "Jessie wonders what otoh means - on the other hand (\"@Jake Penny otoh Americans love to talk to strangers randomly\" - Matthijs Krul)" },
    { time: "01:25:56", category: "Chat", text: "\"​Jessie doesnt need to fight, she can break people with her eyes if she wants to\" - Noel Strüning" },
    { time: "01:26:16", category: "Main", text: "Jessie mentions 2 things: There's 30 minutes left and need to think about a Poll. July 1st will be a new podcast release. David mentions thing 3: This episode will end slightly (5 minutes) early for a chat for a new movie they are working on." },
    { time: "01:28:58", category: "Main", text: "David is on last two glyphs with diacritics, and asks Jessie how the diacritics should be centered on them." },
    { time: "01:31:16", category: "Chat", text: "Diacritic centered above middle line? (\"​My gut says middle line, but the white space seems intriguing\" - Miles)" },
    { time: "01:31:48", category: "Main", text: "Jessie suspects diminutives for nouns and verbal derivatioons haven't been done yet. The only nominal derivation is an augmentative." },
    { time: "01:32:58", category: "Main", text: "David having font problems" },
    { time: "01:33:54", category: "Chat Question", text: "No greetings yet in Tpaalha (\"​Have any greetings and such been done?\" - Miles)" },
    { time: "01:34:06", category: "Chat Poll", text: "Position of diacritic: centered over center line, centered right of center line, or centered over whitespace between vertical lines. The third option wins." },
    { time: "01:35:53", category: "Chat Poll", text: "Position of diacritic over character with just vertical line: extend midline to left to accomodate diacritic to left?" },
    { time: "01:35:59", category: "Chat", text: "\"​special accent?\" - Jake Penny" },
    { time: "01:37:06", category: "Chat", text: "\"It remids me of Ί Έ Ό ... ​Like greek capital letters\" - Noel Strüning" },
    { time: "01:38:10", category: "Chat", text: "\"dash through a la ł?\" - Jake Penny" },
    { time: "01:38:23", category: "Main", text: "David creates new glyphs for poll: diacritic, dash near top, top bar, or top bar with serifs" },
    { time: "01:40:18", category: "Chat", text: "David: \"Plop on down like a pumpkin\"" },
    { time: "01:41:37", category: "Main", text: "David is disgusted at incorrect angle of glyph" },
    { time: "01:43:06", category: "Chat", text: "David's friend's text message" },
    { time: "01:43:52", category: "Chat", text: "\"That needs fixed\"" },
    { time: "01:44:04", category: "Chat", text: "\"​sorry was cleaning the keyboard, had greasy pizza paws over it ... thanks Jessie\" - Rag Doll" },
    { time: "01:44:22", category: "Chat", text: "Song by the decemberists, \"Everything is Aweful\"" },
    { time: "01:44:59", category: "Chat Question", text: "\"Isn't that song in the Lego Movie?\" - Miles" },
    { time: "01:45:47", category: "Chat", text: "Movie: The Last Dragon (1985)" },
    { time: "01:46:55", category: "Chat", text: "Nuthach (\"a nuthatch is a small bird that can walk around on tree bark in all directions in search of bugs to eat. they also sometimes stuff food in crevices and peck at it (to open seeds, etc)\" - Jonathan)" },
    { time: "01:47:38", category: "Main", text: "David asks how to center the top bar of the glyph" },
    { time: "01:49:42", category: "Chat", text: "The Boondocks" },
    { time: "01:51:30", category: "Main", text: "David tries one more glyph for the poll, making 5 options in total" },
    { time: "01:54:39", category: "Main", text: "End" },
]
const episode235Fuse = new Fuse(episode235, { findAllMatches: true, shouldSort: true, includeScore: true, keys: [{ name: 'category', weight: 0.7 }, { name: 'text', weight: 0.3 }], threshold: 0.5, distance: 120 })

var app = new Vue({
    el: "#app",
    methods: {
        getUrl: function(timeString) {
            colonCount = (timeString.match(/:/g)).length
            if (colonCount == 2) {
                time = moment(timeString, 'HH:mm:ss')
            } else {
                time = moment(timeString, 'mm:ss')
            }
            seconds = time.seconds() + (time.minutes() * 60) + (time.hours() * 60 * 60)
            return this.getCurrentEpisode().url + "&t=" + seconds + "s";
        },
        showIndex: function() {
            this.page = "index";
            this.episodeShown = false;
            this.indexShown = true;
            this.search = "";
            this.currentEpisode = "";
        },
        showEpisode: function(ep) {
            this.search = "";
            this.page = "episode";
            this.indexShown = false;
            this.episodeShown = true;
            this.currentEpisode = ep;
        },
        getCurrentEpisode: function() {
            if (this.currentEpisode == "235") {
                return { data: this.episode235, fuse: episode235Fuse, url: episode235Url, name: "235" }
            } else if (this.currentEpisode == "236") {
                return { data: this.episode236, fuse: episode236Fuse, url: episode236Url, name: "236" }
            }
        },
    },
    computed: {
        getEpisodeInfo: function() {
            var that = this;
            if (this.search == "") {
                return this.getCurrentEpisode().data.filter((annotation) => {
                    return (annotation.category == "" && that.mainFilter)
                        || (annotation.category == "Poll" && that.pollFilter)
                        || (annotation.category == "Chat" && that.chatFilter)
                        || (annotation.category == "Chat Question" && that.chatQuestionFilter)
                        || (annotation.category == "Chat Poll" && that.chatPollFilter)
                        || (annotation.category == "Kopiko Time" && that.kopikoTimeFilter);
                })
            }
            return this.getCurrentEpisode().fuse.search(this.search).filter((annotation) => {
                return (annotation.item.category == "" && that.mainFilter)
                    || (annotation.item.category == "Poll" && that.pollFilter)
                    || (annotation.item.category == "Chat" && that.chatFilter)
                    || (annotation.item.category == "Chat Question" && that.chatQuestionFilter)
                    || (annotation.item.category == "Chat Poll" && that.chatPollFilter)
                    || (annotation.item.category == "Kopiko Time" && that.kopikoTimeFilter);
            })
        },
    },
    data: {
        episode235: episode235,
        episode236: episode236,
        index: index,
        search: "",
        indexShown: true,
        episodeShown: false,
        page: "index", // index or episode
        currentEpisode: "",

        mainFilter: true,
        pollFilter: true,
        chatFilter: true,
        chatQuestionFilter: true,
        chatPollFilter: true,
        kopikoTimeFilter: true,
    }
})